/*
 * Copyright 2024-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 */
package com.sn68.agent.dataagent.optimization.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.sn68.agent.dataagent.dto.ModelConfigDTO;
import com.sn68.agent.dataagent.enums.ModelType;
import com.sn68.agent.dataagent.optimization.dto.OptCandidateRequest;
import com.sn68.agent.dataagent.optimization.enums.AgentOptimizationErrorDict;
import com.sn68.agent.dataagent.properties.DataAgentProperties;
import com.sn68.agent.dataagent.service.aimodelconfig.DynamicModelFactory;
import com.sn68.agent.dataagent.service.aimodelconfig.ModelConfigDataService;
import com.sn68.agent.framework.commons.exception.CheckedException;
import java.nio.charset.StandardCharsets;
import org.junit.jupiter.api.Test;
import org.springframework.ai.chat.model.ChatModel;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.ai.chat.model.Generation;
import org.springframework.ai.chat.messages.AssistantMessage;
import org.springframework.ai.chat.prompt.Prompt;
import org.springframework.http.HttpHeaders;
import org.springframework.web.reactive.function.client.WebClientResponseException;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

class OptCandidateGeneratorTest {

	private final DataAgentProperties properties = new DataAgentProperties();

	private final ModelConfigDataService modelConfigDataService = mock(ModelConfigDataService.class);

	private final DynamicModelFactory dynamicModelFactory = mock(DynamicModelFactory.class);

	private final OptCandidateGenerator generator = new OptCandidateGenerator(properties, modelConfigDataService,
			dynamicModelFactory, new ObjectMapper());

	@Test
	void autoGenerateDisabledByDefault() {
		assertEquals(false, generator.autoGenerateEnabled());
	}

	@Test
	void sanitizeRedactsEmailAndTruncates() {
		String sanitized = OptCandidateGenerator.sanitize("联系 user@example.com 订单 1234567890123 " + "x".repeat(500),
				220);
		assertTrue(sanitized.contains("[email]"));
		assertTrue(sanitized.contains("[id]"));
		assertEquals(220, sanitized.length());
	}

	@Test
	void generateParsesModelJson() {
		ModelConfigDTO config = new ModelConfigDTO();
		when(modelConfigDataService.getActiveRuntimeConfigByType(ModelType.CHAT)).thenReturn(config);
		ChatModel chatModel = mock(ChatModel.class);
		when(dynamicModelFactory.createChatModel(config)).thenReturn(chatModel);
		when(chatModel.call(any(Prompt.class))).thenReturn(new ChatResponse(java.util.List.of(new Generation(
				new AssistantMessage("{\"targetType\":\"PROMPT\",\"candidateName\":\"修提示词\",\"changeReason\":\"命中失败聚类\",\"patchJson\":{\"snapshotOverlay\":{\"promptSnapshot\":{\"prompt\":\"请先核对账单月份\"}}}}")))));

		OptCandidateRequest request = generator.generate("PROMPT", "300", null, "failureReasons=CODE_ORACLE_MISMATCH");

		assertEquals("PROMPT", request.getTargetType());
		assertEquals("300", request.getTargetId());
		assertEquals("llm", request.getGeneratedBy());
		assertTrue(request.getPatchJson().contains("promptSnapshot"));
	}

	@Test
	void generateFailsClosedOnInvalidJson() {
		ModelConfigDTO config = new ModelConfigDTO();
		when(modelConfigDataService.getActiveRuntimeConfigByType(ModelType.CHAT)).thenReturn(config);
		ChatModel chatModel = mock(ChatModel.class);
		when(dynamicModelFactory.createChatModel(config)).thenReturn(chatModel);
		when(chatModel.call(any(Prompt.class)))
			.thenReturn(new ChatResponse(java.util.List.of(new Generation(new AssistantMessage("不是 JSON")))));

		CheckedException ex = assertThrows(CheckedException.class,
				() -> generator.generate("PROMPT", "300", null, "trace"));

		assertEquals(AgentOptimizationErrorDict.GENERATE_FAILED.getValue(), ex.getCode());
	}

	@Test
	void generateRetriesOn429ThenParsesJson() {
		ModelConfigDTO config = new ModelConfigDTO();
		when(modelConfigDataService.getActiveRuntimeConfigByType(ModelType.CHAT)).thenReturn(config);
		ChatModel chatModel = mock(ChatModel.class);
		when(dynamicModelFactory.createChatModel(config)).thenReturn(chatModel);
		when(chatModel.call(any(Prompt.class))).thenThrow(httpError(429)).thenReturn(successResponse());

		OptCandidateRequest request = generator.generate("PROMPT", "300", null, "failureReasons=CODE_ORACLE_MISMATCH");

		assertEquals("PROMPT", request.getTargetType());
		assertEquals("300", request.getTargetId());
		assertEquals("llm", request.getGeneratedBy());
		assertTrue(request.getPatchJson().contains("promptSnapshot"));
		verify(chatModel, times(2)).call(any(Prompt.class));
	}

	@Test
	void generateFailsClosedOn400WithoutTreatingAsSuccess() {
		ModelConfigDTO config = new ModelConfigDTO();
		when(modelConfigDataService.getActiveRuntimeConfigByType(ModelType.CHAT)).thenReturn(config);
		ChatModel chatModel = mock(ChatModel.class);
		when(dynamicModelFactory.createChatModel(config)).thenReturn(chatModel);
		when(chatModel.call(any(Prompt.class))).thenThrow(httpError(400)).thenReturn(successResponse());

		CheckedException ex = assertThrows(CheckedException.class,
				() -> generator.generate("PROMPT", "300", null, "trace"));

		assertEquals(AgentOptimizationErrorDict.GENERATE_FAILED.getValue(), ex.getCode());
		verify(chatModel, times(1)).call(any(Prompt.class));
	}

	private static ChatResponse successResponse() {
		return new ChatResponse(java.util.List.of(new Generation(new AssistantMessage(
				"{\"targetType\":\"PROMPT\",\"candidateName\":\"修提示词\",\"changeReason\":\"命中失败聚类\",\"patchJson\":{\"snapshotOverlay\":{\"promptSnapshot\":{\"prompt\":\"请先核对账单月份\"}}}}"))));
	}

	private static WebClientResponseException httpError(int status) {
		return WebClientResponseException.create(status, "HTTP " + status, HttpHeaders.EMPTY, new byte[0],
				StandardCharsets.UTF_8);
	}

}
