-- Demo business schema for order/bill agents. Generated, do not edit by hand.
-- Month window: 2026-09-01 .. 2026-10-01
CREATE SCHEMA IF NOT EXISTS demo_biz;
SET search_path TO demo_biz, public;

DROP TABLE IF EXISTS demo_biz."dis_demand" CASCADE;
CREATE TABLE demo_biz."dis_demand" (
  "id" character varying(36),
  "demand_no" character varying(50),
  "erp_order_no" character varying(128),
  "company_id" character varying(36),
  "company_name" character varying(255),
  "industry_id" character varying(50),
  "industry_name" character varying(255),
  "type" character varying(2),
  "business_type" character varying(50),
  "arrival_time" timestamp without time zone,
  "remark" text,
  "demand_num" integer,
  "todo_num" integer,
  "ing_num" integer,
  "sign_num" integer,
  "reason" character varying(200),
  "cancel_id" character varying(36),
  "cancel_name" character varying(50),
  "cancel_time" timestamp(0) without time zone,
  "contract_code" character varying(50),
  "return_reason" character varying(200),
  "fast_remark" character varying(255),
  "car_length" character varying(255),
  "package_mode" character varying(255),
  "status" character varying(2),
  "return_type" character varying(100),
  "return_demand_no" character varying(50),
  "source_type" character varying(20),
  "mall_order_id" character varying(32),
  "mall_order_no" character varying(64),
  "ref_bill_no" character varying(36),
  "file_name" character varying(2000),
  "release_type" character varying(36),
  "is_release" boolean,
  "custom_order_no" character varying(255),
  "custom_delivery_no" character varying(255),
  "one_project_id" character varying(36),
  "one_project_name" character varying(255),
  "two_project_id" character varying(36),
  "two_project_name" character varying(255),
  "target_one_project_id" character varying(36),
  "target_one_project_name" character varying(255),
  "target_two_project_id" character varying(36),
  "target_two_project_name" character varying(255),
  "sales_manager_id" character varying(36),
  "sales_manager_name" character varying(255),
  "sales_team_id" character varying(36),
  "sales_team_name" character varying(255),
  "sales_director_id" character varying(36),
  "sales_director_name" character varying(255),
  "deleted" boolean,
  "create_by" character varying(36),
  "create_name" character varying(255),
  "create_time" timestamp(6) without time zone,
  "last_modify_by" character varying(255),
  "last_modify_name" character varying(255),
  "last_modify_time" timestamp(6) with time zone,
  "tenant_id" character varying(50),
  "contract_id" character varying(255),
  "create_tel" character varying(255),
  "process_instance_id" bigint,
  "process_instance_status" character varying(32),
  "cooperation_company_name" character varying(128),
  "cooperation_company_tax_number" character varying(128),
  "bank" character varying(128),
  "bank_account" character varying(128),
  "team_info" text,
  "team_position" text,
  "full_industry_id" character varying(255),
  "full_industry_name" character varying(255),
  "apply_type" integer
);

DROP TABLE IF EXISTS demo_biz."dis_demand_address" CASCADE;
CREATE TABLE demo_biz."dis_demand_address" (
  "id" character varying(36),
  "demand_id" character varying(36),
  "demand_no" character varying(50),
  "type" character varying(2),
  "site_id" character varying(36),
  "site_code" character varying(36),
  "site_type" character varying(100),
  "site_name" character varying(255),
  "site_address" character varying(255),
  "contact" character varying(50),
  "tel" character varying(50),
  "remark" character varying(200),
  "province_id" character varying(36),
  "province_name" character varying(150),
  "city_id" character varying(36),
  "city_name" character varying(36),
  "district_id" character varying(36),
  "district_name" character varying(255),
  "address" character varying(200),
  "full_address" character varying(255),
  "lng" numeric,
  "lat" numeric,
  "addr_flag" smallint,
  "deleted" boolean,
  "create_by" character varying(36),
  "create_name" character varying(255),
  "create_time" timestamp(6) without time zone,
  "last_modify_by" character varying(255),
  "last_modify_name" character varying(255),
  "last_modify_time" timestamp(6) with time zone,
  "company_id" character varying(36),
  "company_name" character varying(64)
);

DROP TABLE IF EXISTS demo_biz."dis_demand_product" CASCADE;
CREATE TABLE demo_biz."dis_demand_product" (
  "id" character varying(36),
  "demand_id" character varying(36),
  "demand_no" character varying(50),
  "erp_code" character varying(255),
  "product_id" character varying(36),
  "product_no" character varying(255),
  "product_name" character varying(255),
  "product_kit_id" character varying(36),
  "size_length" numeric(24,6),
  "size_width" numeric(24,6),
  "size_height" numeric(24,6),
  "expand_volume" numeric(24,6),
  "fold_volume" numeric(24,6),
  "unit_weight" numeric(24,6),
  "unit_volume" numeric(24,6),
  "num" integer,
  "dispatch_num" integer,
  "add_num" integer,
  "tonnage" numeric(15,2),
  "remark" character varying(200),
  "group_id" character varying(36),
  "clean_status" character varying(2),
  "send_order_product_id" character varying(36),
  "deleted" boolean,
  "create_by" character varying(36),
  "create_name" character varying(255),
  "create_time" timestamp(6) without time zone,
  "last_modify_by" character varying(255),
  "last_modify_name" character varying(255),
  "last_modify_time" timestamp(6) with time zone,
  "product_type" character varying(255),
  "support_scan" boolean,
  "product_price" numeric(10,2)
);

DROP TABLE IF EXISTS demo_biz."dis_order" CASCADE;
CREATE TABLE demo_biz."dis_order" (
  "id" character varying(36),
  "order_no" character varying(50),
  "ymm_no" character varying(100),
  "status" character varying(2),
  "carrier_id" character varying(255),
  "carrier_name" character varying(255),
  "driver_id" character varying(255),
  "driver_name" character varying(255),
  "id_card" character varying(128),
  "tel" character varying(36),
  "car_no" character varying(20),
  "car_model" character varying(20),
  "car_length" character varying(255),
  "carry_type" character varying(200),
  "transport_mode" character varying(20),
  "pre_begin_time" timestamp(0) without time zone,
  "pre_end_time" timestamp(0) without time zone,
  "base_price" numeric(15,2),
  "freight" numeric(15,2),
  "add_fee" numeric(15,2),
  "tax_rate" numeric(15,6),
  "unit_price" numeric(15,2),
  "total_incl_tax" numeric(15,2),
  "remark" character varying(200),
  "operator_id" character varying(50),
  "operator_tel" character varying(20),
  "operator_name" character varying(64),
  "operation_time" timestamp(0) without time zone,
  "op_remark" character varying(200),
  "reason" character varying(200),
  "cancel_id" character varying(50),
  "cancel_name" character varying(50),
  "cancel_time" timestamp(0) without time zone,
  "sum_weight" numeric(15,2),
  "sum_volume" numeric(15,2),
  "guide_amount" numeric(15,2),
  "transport_price" numeric(15,2),
  "safe_fee" numeric(15,2),
  "load_fee" numeric(15,2),
  "from_fee" numeric(15,2),
  "to_fee" numeric(15,2),
  "wait_fee" numeric(15,2),
  "empty_fee" numeric(15,2),
  "total_excl_tax" numeric(15,2),
  "adjust_reason" character varying(255),
  "adjust_remark" character varying(255),
  "designate_id" character varying(50),
  "designate_name" character varying(50),
  "driver_images" character varying(255),
  "logistics_insurance_no" character varying(255),
  "logistics_no" character varying(255),
  "load_images" character varying(2000),
  "real_sum_weight" numeric(15,2),
  "real_sum_volume" character varying(255),
  "real_remark" character varying(255),
  "finish_time" timestamp(6) without time zone,
  "insured" character varying(2),
  "insure_id" character varying(36),
  "insure_name" character varying(255),
  "insure_time" timestamp(6) without time zone,
  "rule_trans_fee" double precision,
  "package_weight" double precision,
  "package_volume" double precision,
  "charged_type" character varying(50),
  "conversion_rate" double precision,
  "line_type" character varying(50),
  "rule_no" character varying(50),
  "tenant_id" character varying(255),
  "deleted" boolean,
  "create_tel" character varying(255),
  "create_by" character varying(36),
  "create_name" character varying(255),
  "create_time" timestamp(6) without time zone,
  "last_modify_by" character varying(36),
  "last_modify_name" character varying(255),
  "last_modify_time" timestamp(6) without time zone,
  "id_card_search" character varying(128),
  "theoretical_square" character varying(36),
  "other_fee" numeric(15,2),
  "physical_weight" double precision,
  "physical_volume" double precision,
  "loading_specs_ext" text,
  "memo_ext" text,
  "process_instance_id" bigint,
  "process_instance_status" character varying(32),
  "exception_ext" text
);

DROP TABLE IF EXISTS demo_biz."dis_order_address" CASCADE;
CREATE TABLE demo_biz."dis_order_address" (
  "id" character varying(36),
  "order_id" character varying(36),
  "order_no" character varying(50),
  "demand_id" character varying(36),
  "demand_no" character varying(36),
  "type" character varying(2),
  "site_id" character varying(36),
  "site_code" character varying(255),
  "site_name" character varying(255),
  "site_address" character varying(255),
  "site_type" character varying(100),
  "contact" character varying(50),
  "tel" character varying(64),
  "remark" character varying(200),
  "province_id" character varying(36),
  "province_name" character varying(150),
  "city_id" character varying(36),
  "city_name" character varying(150),
  "district_id" character varying(36),
  "district_name" character varying(255),
  "full_address" character varying(200),
  "address" character varying(255),
  "lng" numeric,
  "lat" numeric,
  "deleted" boolean,
  "create_by" character varying(36),
  "create_name" character varying(255),
  "create_time" timestamp(6) without time zone,
  "last_modify_by" character varying(36),
  "last_modify_name" character varying(255),
  "last_modify_time" timestamp(6) without time zone,
  "company_id" character varying(36),
  "company_name" character varying(255),
  "tenant_id" character varying(64)
);

DROP TABLE IF EXISTS demo_biz."dis_order_product" CASCADE;
CREATE TABLE demo_biz."dis_order_product" (
  "id" character varying(50),
  "demand_id" character varying(50),
  "demand_no" character varying(50),
  "order_id" character varying(50),
  "order_no" character varying(50),
  "status" character varying(20),
  "product_id" character varying(50),
  "product_name" character varying(255),
  "product_no" character varying(255),
  "product_unit" character varying(255),
  "volume" numeric(15,2),
  "weight" numeric(15,2),
  "vw_value" numeric(15,2),
  "demand_num" integer,
  "dispatch_num" integer,
  "out_num" integer,
  "sign_num" integer,
  "add_num" integer,
  "charged_type" character varying(255),
  "untaxed_freight_fee" numeric(15,2),
  "abnormal_type" character varying(255),
  "abnormal_reason" character varying(255),
  "settlement_time" timestamp(6) without time zone,
  "freight_fee" numeric(15,2),
  "remark" character varying(1000),
  "out_operator_id" character varying(255),
  "out_operation_time" timestamp(6) with time zone,
  "out_operator_name" character varying(50),
  "out_operator_tel" character varying(20),
  "out_time" timestamp(0) without time zone,
  "out_param" text,
  "sign_operator_id" character varying(255),
  "sign_operation_time" timestamp(6) with time zone,
  "sign_operator_name" character varying(50),
  "sign_operator_tel" character varying(20),
  "sign_time" timestamp(6) without time zone,
  "sign_action_time" timestamp(6) with time zone,
  "sign_customer_receipt" character varying(1000),
  "sign_other_receipt" character varying(1000),
  "sign_remark" character varying(1000),
  "sign_receipt_operator_id" character varying(64),
  "sign_receipt_operator_name" character varying(64),
  "sign_receipt_operator_tel" character varying(64),
  "sign_receipt_operation_time" timestamp(6) without time zone,
  "sign_type" smallint,
  "group_id" character varying(36),
  "deleted" boolean,
  "create_by" character varying(36),
  "create_name" character varying(255),
  "create_time" timestamp(6) without time zone,
  "last_modify_by" character varying(255),
  "last_modify_name" character varying(255),
  "last_modify_time" timestamp(6) with time zone,
  "size_length" numeric(15,4),
  "size_width" numeric(15,4),
  "size_height" numeric(15,4),
  "expand_volume" numeric(15,4),
  "fold_volume" numeric(15,4),
  "unit_weight" numeric(15,4),
  "unit_volume" numeric(15,4),
  "product_type" character varying(20),
  "support_scan" boolean,
  "product_kit_id" character varying(255),
  "erp_code" character varying(255),
  "product_price" numeric(10,2),
  "demand_product_id" character varying(36),
  "out_type" smallint,
  "source_type" smallint,
  "out_scan_num" integer,
  "sign_scan_num" integer,
  "distance" numeric(10,2),
  "tenant_id" character varying(64)
);

DROP TABLE IF EXISTS demo_biz."additional_cost" CASCADE;
CREATE TABLE demo_biz."additional_cost" (
  "id" character varying(255),
  "cost_no" character varying(255),
  "cost_type" character varying(255),
  "ref_bill_id" character varying(255),
  "ref_bill_no" character varying(255),
  "company_id" character varying(255),
  "company_name" character varying(255),
  "industry_id" character varying(255),
  "industry_name" character varying(255),
  "period" character varying(255),
  "amount" numeric(19,2),
  "one_project_id" character varying(255),
  "one_project_name" character varying(255),
  "two_project_id" character varying(255),
  "two_project_name" character varying(255),
  "description" text,
  "attachments" text,
  "use_status" integer,
  "approval_status" integer,
  "deleted" boolean,
  "create_by" character varying(36),
  "create_name" character varying(255),
  "create_time" timestamp(6) without time zone,
  "last_modify_by" character varying(255),
  "last_modify_name" character varying(255),
  "last_modify_time" timestamp(6) with time zone,
  "tenant_id" character varying(64)
);

DROP TABLE IF EXISTS demo_biz."additional_cost_item" CASCADE;
CREATE TABLE demo_biz."additional_cost_item" (
  "id" character varying(255),
  "cost_id" character varying(255),
  "item_id" character varying(255),
  "item_name" character varying(255),
  "product_id" character varying(255),
  "product_no" character varying(255),
  "product_name" character varying(255),
  "amount" numeric(19,2),
  "price" numeric(19,2),
  "quantity" integer,
  "description" text,
  "deleted" boolean,
  "create_by" character varying(36),
  "create_name" character varying(255),
  "create_time" timestamp(6) without time zone,
  "last_modify_by" character varying(255),
  "last_modify_name" character varying(255),
  "last_modify_time" timestamp(6) with time zone,
  "item_type" smallint,
  "demand_id" character varying(50),
  "demand_no" character varying(100),
  "order_id" character varying(50),
  "order_no" character varying(100),
  "order_product_id" character varying(50)
);

DROP TABLE IF EXISTS demo_biz."bill_contract" CASCADE;
CREATE TABLE demo_biz."bill_contract" (
  "id" character varying(36),
  "type" character varying(2),
  "code" character varying(50),
  "name" character varying(100),
  "company_id" character varying(36),
  "annual_revenue" numeric(15,6),
  "effective_date" timestamp(6) without time zone,
  "expiration_date" timestamp(6) without time zone,
  "subsist" numeric(15,6),
  "reconciliation_date" integer,
  "period" character varying(100),
  "settlement_node" character varying(2),
  "security_deposit_rate" numeric(15,2),
  "fare" numeric(15,2),
  "duration" integer,
  "status" character varying(2),
  "bill_term" integer,
  "bail" numeric(15,6),
  "fee_node" character varying(2),
  "return_node" character varying(2),
  "rental_charge_type" character varying(2),
  "edit_fields" character varying(2000),
  "period_begin" integer,
  "period_end" integer,
  "settlement_type" character varying(2),
  "warn_day" integer,
  "warn_flag" character varying(2),
  "maintenance_fee_node" character varying(2),
  "overdue_fee" numeric(15,6),
  "file_name" character varying(2000),
  "cycle_type" character varying(2),
  "sign_bill_type" character varying(2),
  "overdue_fee_node" character varying(2),
  "regional_send_node" character varying(2),
  "regional_collect_node" character varying(2),
  "daily_rent_node" character varying(2),
  "enable_status" smallint,
  "business_contract_name" character varying(255),
  "business_contract_code" character varying(255),
  "approval_no" character varying(255),
  "approval_time" timestamp without time zone,
  "products_content" text,
  "teams_content" text,
  "deleted" boolean,
  "create_by" character varying(36),
  "create_name" character varying(255),
  "create_time" timestamp(6) without time zone,
  "last_modify_by" character varying(255),
  "last_modify_name" character varying(255),
  "last_modify_time" timestamp(6) with time zone,
  "company_name" character varying,
  "industry_id" character varying,
  "industry_name" character varying,
  "company_contact_name" character varying,
  "company_tel" character varying,
  "company_mail" character varying,
  "company_address" character varying,
  "one_project_id" character varying,
  "one_project_name" character varying,
  "two_project_id" character varying,
  "two_project_name" character varying,
  "daily_start_time" timestamp without time zone,
  "daily_config" text,
  "bill_scope" character varying,
  "order_rent_config" text,
  "tenant_id" character varying(64)
);

DROP TABLE IF EXISTS demo_biz."bill_contract_product" CASCADE;
CREATE TABLE demo_biz."bill_contract_product" (
  "id" character varying(36),
  "product_id" character varying(36),
  "price" numeric(15,6),
  "fare" numeric(15,6),
  "service_fee" numeric(15,6),
  "maintenance_fee" numeric(15,6),
  "type" character varying(2),
  "contract_id" character varying(36),
  "return_fare" numeric(15,6),
  "edit_fields" character varying(2000),
  "settlement_node" character varying(2),
  "send_fare" numeric(15,6),
  "deleted" boolean,
  "create_by" character varying(36),
  "create_name" character varying(255),
  "create_time" timestamp(6) without time zone,
  "last_modify_by" character varying(255),
  "last_modify_name" character varying(255),
  "last_modify_time" timestamp(6) with time zone,
  "product_no" character varying,
  "product_name" character varying,
  "service_fee_quantity_type" character varying,
  "maintenance_fee_quantity_type" character varying,
  "send_fare_quantity_type" character varying,
  "return_fare_quantity_type" character varying,
  "price_quantity_type" character varying,
  "fare_quantity_type" character varying,
  "order_rent_box_num_type" character varying
);

DROP TABLE IF EXISTS demo_biz."bill_contract_product_route" CASCADE;
CREATE TABLE demo_biz."bill_contract_product_route" (
  "id" character varying(36),
  "contract_product_id" character varying(36),
  "from_site_id" character varying(36),
  "to_site_id" character varying(36),
  "fare" double precision,
  "price" numeric(15,6),
  "edit_fields" character varying(2000),
  "less_num" integer,
  "fare_add_amount" numeric(15,6),
  "service_fee" numeric(15,6),
  "maintenance_fee" numeric(15,6),
  "type" character varying(2),
  "begin_num" numeric(15,2),
  "end_num" numeric(15,2),
  "price_type" character varying(2),
  "fee_node" character varying(2),
  "maintenance_fee_node" character varying(2),
  "return_fare" numeric(15,6),
  "send_fare" numeric(15,6),
  "price1" numeric(15,6),
  "price2" numeric(15,6),
  "price3" numeric(15,6),
  "consumable_fare" numeric(15,6),
  "deleted" boolean,
  "create_by" character varying(36),
  "create_name" character varying(255),
  "create_time" timestamp(6) without time zone,
  "last_modify_by" character varying(255),
  "last_modify_name" character varying(255),
  "last_modify_time" timestamp(6) with time zone,
  "from_site_name" character varying,
  "to_site_name" character varying,
  "service_fee_quantity_type" character varying,
  "maintenance_fee_quantity_type" character varying,
  "send_fare_quantity_type" character varying,
  "return_fare_quantity_type" character varying,
  "price_quantity_type" character varying,
  "order_rent_box_num_type" character varying
);

DROP TABLE IF EXISTS demo_biz."bill_cost" CASCADE;
CREATE TABLE demo_biz."bill_cost" (
  "id" character varying(36),
  "code" character varying(300),
  "company_id" character varying(36),
  "company_name" character varying(100),
  "settlement_node" character varying(2),
  "settlement_date" character varying(100),
  "amount" numeric(15,6),
  "contract_id" character varying(36),
  "contract_code" character varying(50),
  "status" character varying(2),
  "adjust_amount" numeric(15,6),
  "subsist" numeric(15,6),
  "security_deposit_rate" numeric(15,2),
  "contract_type" character varying(2),
  "reconciliation_date" integer,
  "bail" numeric(15,6),
  "is_show" character varying(2),
  "demand_id" character varying(36),
  "demand_no" character varying(50),
  "supervise_status" smallint,
  "merge_id" character varying(36),
  "fare" numeric(16,6),
  "deleted" boolean,
  "create_by" character varying(36),
  "create_name" character varying(255),
  "create_time" timestamp(6) without time zone,
  "last_modify_by" character varying(255),
  "last_modify_name" character varying(255),
  "last_modify_time" timestamp(6) with time zone,
  "industry_id" character varying,
  "industry_name" character varying,
  "statement_attachment" character varying,
  "one_project_id" character varying,
  "one_project_name" character varying,
  "two_project_id" character varying,
  "two_project_name" character varying,
  "cost_from_type" character varying,
  "tenant_id" character varying(64)
);

DROP TABLE IF EXISTS demo_biz."bill_cost_breakdown" CASCADE;
CREATE TABLE demo_biz."bill_cost_breakdown" (
  "id" character varying(36),
  "cost_id" character varying(36),
  "product_id" character varying(36),
  "price" numeric(15,6),
  "fare" numeric(15,6),
  "from_site_id" character varying(36),
  "to_site_id" character varying(36),
  "service_fee" numeric(15,6),
  "maintenance_fee" numeric(15,6),
  "type" character varying(2),
  "num" integer,
  "amount" numeric(15,6),
  "order_product_id" character varying(36),
  "contract_code" character varying(50),
  "settlement_date" date,
  "bill_date" date,
  "return_fare" numeric(15,6),
  "settlement_cycle" character varying(50),
  "settlement_type" character varying(2),
  "bill_term" integer,
  "fare_add_amount" numeric(15,6),
  "consumable_fare" numeric(15,6),
  "price_month" numeric(15,6),
  "days" integer,
  "is_show" character varying(255),
  "data_type" smallint,
  "dispatch_num" integer,
  "out_num" integer,
  "sign_num" integer,
  "send_fare" numeric(15,6),
  "deleted" boolean,
  "create_by" character varying(36),
  "create_name" character varying(255),
  "create_time" timestamp(6) without time zone,
  "last_modify_by" character varying(36),
  "last_modify_name" character varying(255),
  "last_modify_time" timestamp(6) without time zone,
  "product_no" character varying,
  "product_name" character varying,
  "from_site_name" character varying,
  "to_site_name" character varying,
  "demand_type" character varying,
  "contract_type" character varying,
  "return_fare_num" integer,
  "consumable_fare_num" integer,
  "send_fare_num" integer,
  "service_fee_num" integer,
  "maintenance_fee_num" integer,
  "fare_num" integer
);

DROP TABLE IF EXISTS demo_biz."bill_cost_return" CASCADE;
CREATE TABLE demo_biz."bill_cost_return" (
  "id" character varying(36),
  "demand_id" character varying(36),
  "demand_no" character varying(50),
  "return_type" character varying(100),
  "return_demand_no" character varying(50),
  "contract_id" character varying(36),
  "contract_code" character varying(50),
  "product_id" character varying(100),
  "product_name" character varying(255),
  "num" integer,
  "price" numeric(15,6),
  "amount" numeric(15,6),
  "cost_id" character varying(36),
  "days" integer,
  "deleted" boolean,
  "create_by" character varying(36),
  "create_name" character varying(255),
  "create_time" timestamp(6) without time zone,
  "last_modify_by" character varying(255),
  "last_modify_name" character varying(255),
  "last_modify_time" timestamp(6) with time zone,
  "product_no" character varying,
  "order_product_id" character varying
);

DROP TABLE IF EXISTS demo_biz."daily_product_num" CASCADE;
CREATE TABLE demo_biz."daily_product_num" (
  "id" character varying,
  "company_id" character varying,
  "company_name" character varying,
  "one_project_id" character varying,
  "one_project_name" character varying,
  "two_project_id" character varying,
  "two_project_name" character varying,
  "industry_id" character varying,
  "industry_name" character varying,
  "product_id" character varying,
  "product_name" character varying,
  "product_no" character varying,
  "month" character varying,
  "daily_num" integer,
  "deleted" boolean,
  "create_by" character varying(36),
  "create_name" character varying(255),
  "create_time" timestamp(6) without time zone,
  "last_modify_by" character varying(255),
  "last_modify_name" character varying(255),
  "last_modify_time" timestamp(6) with time zone,
  "daily_assets_quantity" integer,
  "settlement_no" character varying,
  "tenant_id" character varying(64)
);

DROP TABLE IF EXISTS demo_biz."daily_rent_cost" CASCADE;
CREATE TABLE demo_biz."daily_rent_cost" (
  "id" character varying,
  "cost_no" character varying,
  "company_id" character varying,
  "company_name" character varying,
  "settlement_no" character varying,
  "contract_type" character varying,
  "one_project_id" character varying,
  "one_project_name" character varying,
  "two_project_id" character varying,
  "two_project_name" character varying,
  "industry_id" character varying,
  "industry_name" character varying,
  "settlement_date" character varying,
  "daily_rent_amount" numeric,
  "daily_rent_day" integer,
  "daily_rent_assets_quantity" integer,
  "total_daily_rent_day" integer,
  "total_daily_rent_assets_quantity" integer,
  "total_daily_rent_amount" numeric,
  "status" integer,
  "ref_cost_id" character varying,
  "ref_cost_no" character varying,
  "deleted" boolean,
  "create_by" character varying(36),
  "create_name" character varying(255),
  "create_time" timestamp(6) without time zone,
  "last_modify_by" character varying(255),
  "last_modify_name" character varying(255),
  "last_modify_time" timestamp(6) with time zone,
  "return_fee_day" integer,
  "return_fee_amount" numeric,
  "current_charge_start_assets_quantity" integer,
  "current_charge_end_assets_quantity" integer,
  "total_charge_start_assets_quantity" integer,
  "total_charge_end_assets_quantity" integer,
  "return_deduction_day" integer,
  "return_deduction_amount" numeric,
  "receive_rent_day" integer,
  "receive_rent_amount" numeric,
  "total_remain_return_num" integer,
  "process_instance_id" bigint,
  "process_instance_status" character varying(32),
  "tenant_id" character varying(64)
);

DROP TABLE IF EXISTS demo_biz."daily_rent_cost_return" CASCADE;
CREATE TABLE demo_biz."daily_rent_cost_return" (
  "id" character varying(36),
  "demand_id" character varying(36),
  "demand_no" character varying(50),
  "return_type" character varying(100),
  "return_demand_no" character varying(50),
  "contract_id" character varying(36),
  "contract_code" character varying(50),
  "product_id" character varying(100),
  "product_name" character varying(255),
  "num" integer,
  "price" numeric(15,6),
  "amount" numeric(15,6),
  "cost_id" character varying(36),
  "days" integer,
  "deleted" boolean,
  "create_by" character varying(36),
  "create_name" character varying(255),
  "create_time" timestamp(6) without time zone,
  "last_modify_by" character varying(255),
  "last_modify_name" character varying(255),
  "last_modify_time" timestamp(6) with time zone,
  "product_no" character varying,
  "return_order_product_id" character varying
);

DROP TABLE IF EXISTS demo_biz."daily_rent_order_product" CASCADE;
CREATE TABLE demo_biz."daily_rent_order_product" (
  "id" character varying,
  "cost_id" character varying,
  "settlement_date" character varying,
  "order_product_id" character varying,
  "demand_no" character varying,
  "order_no" character varying,
  "product_id" character varying,
  "product_no" character varying,
  "product_name" character varying,
  "settlement_no" character varying,
  "sign_time" timestamp without time zone,
  "order_sign_num" integer,
  "return_num" integer,
  "total_return_num" integer,
  "daily_rent_price" numeric,
  "daily_rent_amount" numeric,
  "daily_rent_day" integer,
  "remain_return_num" integer,
  "deleted" boolean,
  "create_by" character varying(36),
  "create_name" character varying(255),
  "create_time" timestamp(6) without time zone,
  "last_modify_by" character varying(255),
  "last_modify_name" character varying(255),
  "last_modify_time" timestamp(6) with time zone,
  "out_completed" boolean,
  "receive_rent_amount" numeric,
  "return_fee_day" integer,
  "return_fee_amount" numeric
);

DROP TABLE IF EXISTS demo_biz."order_rent_cost" CASCADE;
CREATE TABLE demo_biz."order_rent_cost" (
  "id" character varying(36),
  "cost_no" character varying(64),
  "company_id" character varying(64),
  "company_name" character varying(255),
  "settlement_no" character varying(64),
  "contract_type" character varying(32),
  "one_project_id" character varying(64),
  "one_project_name" character varying(255),
  "two_project_id" character varying(64),
  "two_project_name" character varying(255),
  "industry_id" character varying(64),
  "industry_name" character varying(255),
  "settlement_date" character varying,
  "order_rent_amount" numeric,
  "order_rent_day" integer,
  "order_box_num" integer,
  "total_order_rent_day" integer,
  "total_order_box_num" integer,
  "total_order_rent_amount" numeric,
  "status" integer,
  "ref_cost_id" character varying(32),
  "ref_cost_no" character varying(64),
  "process_instance_id" bigint,
  "process_instance_status" character varying(255),
  "create_by" character varying(32),
  "create_name" character varying(255),
  "create_time" timestamp without time zone,
  "last_modify_by" character varying(32),
  "last_modify_name" character varying(255),
  "last_modify_time" timestamp without time zone,
  "deleted" boolean
);

DROP TABLE IF EXISTS demo_biz."order_rent_cost_product" CASCADE;
CREATE TABLE demo_biz."order_rent_cost_product" (
  "id" character varying(36),
  "cost_id" character varying(36),
  "settlement_date" character varying,
  "product_id" character varying(36),
  "product_no" character varying(64),
  "product_name" character varying(255),
  "settlement_no" character varying(64),
  "contract_type" character varying(32),
  "in_order_product_id" character varying(36),
  "in_order_id" character varying(36),
  "in_order_no" character varying(64),
  "in_demand_id" character varying(36),
  "in_demand_no" character varying(64),
  "in_source_company_id" character varying(36),
  "in_source_company_name" character varying(255),
  "in_target_company_id" character varying(36),
  "in_target_company_name" character varying(255),
  "in_demand_create_time" timestamp without time zone,
  "in_demand_out_time" timestamp without time zone,
  "in_demand_out_num" integer,
  "in_demand_sign_time" timestamp without time zone,
  "in_demand_sign_num" integer,
  "in_business_type" character varying(32),
  "out_demand_type" character varying(64),
  "out_order_product_id" character varying(36),
  "out_order_no" character varying(64),
  "out_order_id" character varying(36),
  "out_demand_no" character varying(64),
  "out_demand_id" character varying(36),
  "rent_price" numeric,
  "charge_start_time" timestamp without time zone,
  "charge_end_time" timestamp without time zone,
  "expense_day" integer,
  "box_num" integer,
  "neg_num" integer,
  "rent_sum_day" integer,
  "current_balance_num" integer,
  "detail_id" character varying(36),
  "create_by" character varying(36),
  "create_name" character varying(255),
  "create_time" timestamp without time zone,
  "last_modify_by" character varying(36),
  "last_modify_name" character varying(255),
  "last_modify_time" timestamp without time zone,
  "deleted" boolean,
  "data_tag" character varying(2),
  "in_demand_type" character varying(64),
  "rent_amount" numeric,
  "in_from_site_id" character varying,
  "in_from_site_name" character varying,
  "in_to_site_id" character varying,
  "in_to_site_name" character varying
);

DROP TABLE IF EXISTS demo_biz."overdue_bill" CASCADE;
CREATE TABLE demo_biz."overdue_bill" (
  "id" character varying(36),
  "cost_no" character varying(100),
  "company_id" character varying(128),
  "company_name" character varying(128),
  "settlement_date" character varying(128),
  "overdue_amount" numeric(15,6),
  "current_overdue_day" integer,
  "current_early_return_day" integer,
  "current_overdue_assets_quantity" integer,
  "current_early_return_assets_quantity" integer,
  "current_early_return_deduction_amount" integer,
  "total_overdue_day" integer,
  "total_overdue_assets_quantity" integer,
  "total_early_return_day" integer,
  "total_early_return_assets_quantity" integer,
  "total_overdue_amount" numeric(15,6),
  "total_early_return_deduction_amount" numeric(15,6),
  "status" integer,
  "back_charge_return_day" integer,
  "back_charge_return_amount" numeric(15,6),
  "deleted" boolean,
  "create_by" character varying(36),
  "create_name" character varying(255),
  "create_time" timestamp(6) without time zone,
  "last_modify_by" character varying(255),
  "last_modify_name" character varying(255),
  "last_modify_time" timestamp(6) with time zone,
  "industry_id" character varying,
  "industry_name" character varying,
  "one_project_id" character varying,
  "one_project_name" character varying,
  "two_project_id" character varying,
  "two_project_name" character varying,
  "ref_cost_id" character varying,
  "ref_cost_no" character varying,
  "process_instance_id" bigint,
  "process_instance_status" character varying(32),
  "return_fee_day" integer,
  "return_fee_amount" numeric,
  "receive_rent_day" integer,
  "receive_rent_amount" numeric,
  "total_remain_return_num" integer,
  "settlement_no" character varying,
  "contract_type" character varying,
  "daily_rent_day" integer,
  "daily_assets_quantity" integer,
  "return_fee_overdue_day" integer,
  "return_fee_overdue_amount" numeric,
  "daily_settlement_no" character varying,
  "overdue_price" numeric,
  "return_fee_overdue_quantity" integer,
  "tenant_id" character varying(64)
);

DROP TABLE IF EXISTS demo_biz."overdue_rent_order_product" CASCADE;
CREATE TABLE demo_biz."overdue_rent_order_product" (
  "id" character varying,
  "cost_id" character varying,
  "settlement_date" character varying,
  "order_product_id" character varying,
  "demand_no" character varying,
  "order_no" character varying,
  "product_id" character varying,
  "product_no" character varying,
  "product_name" character varying,
  "settlement_no" character varying,
  "sign_time" timestamp without time zone,
  "order_sign_num" integer,
  "return_num" integer,
  "total_return_num" integer,
  "overdue_expenses_price" numeric,
  "overdue_expenses_amount" numeric,
  "overdue_expenses_day" integer,
  "remain_return_num" integer,
  "deleted" boolean,
  "create_by" character varying(36),
  "create_name" character varying(255),
  "create_time" timestamp(6) without time zone,
  "last_modify_by" character varying(255),
  "last_modify_name" character varying(255),
  "last_modify_time" timestamp(6) with time zone,
  "out_completed" boolean,
  "receive_rent_amount" numeric,
  "return_fee_day" integer,
  "return_fee_amount" numeric,
  "charge_start_time" timestamp without time zone,
  "charge_end_time" timestamp without time zone,
  "daily_rent_day" integer,
  "daily_assets_quantity" integer,
  "overdue_assets_quantity" integer,
  "return_fee_overdue_day" integer,
  "receive_rent_day" integer,
  "return_fee_overdue_amount" numeric
);

DROP TABLE IF EXISTS demo_biz."project_bill_detail" CASCADE;
CREATE TABLE demo_biz."project_bill_detail" (
  "id" character varying(64),
  "tenant_id" character varying(64),
  "code" character varying(64),
  "type" character varying(32),
  "status" character varying(32),
  "period" character varying(16),
  "year" character varying(8),
  "month" character varying(4),
  "cooperate_subject" character varying(128),
  "cooperate_subject_id" character varying(64),
  "csr_id" text,
  "csr_name" text,
  "sales_manager_id" text,
  "sales_manager_name" text,
  "sales_director_id" text,
  "sales_director_name" text,
  "sales_team_id" character varying(64),
  "sales_team_name" character varying(128),
  "order_product_id" character varying(64),
  "demand_id" character varying(64),
  "demand_no" character varying(64),
  "order_id" character varying(64),
  "order_no" character varying(64),
  "business_type" character varying(32),
  "demand_type" character varying(32),
  "product_id" character varying(64),
  "product_no" character varying(64),
  "product_name" character varying(256),
  "product_type" character varying(32),
  "out_num" integer,
  "out_time" timestamp(6) without time zone,
  "sign_num" integer,
  "sign_time" timestamp(6) without time zone,
  "daily_num" integer,
  "overdue_num" integer,
  "order_rent_num" integer,
  "order_product_status" character varying(8),
  "receipt_type" character varying(32),
  "contract_id" character varying(64),
  "contract_code" character varying(64),
  "contract_name" character varying(256),
  "contract_type" character varying(32),
  "settlement_node" character varying(32),
  "effective_date" timestamp(6) without time zone,
  "expiration_date" timestamp(6) without time zone,
  "receipt_ratio" numeric(18,6),
  "receipt_num" numeric(18,6),
  "operation_num" numeric(18,6),
  "lease_price" numeric(18,6),
  "lease_exclude_tax_price" numeric(18,6),
  "lease_trade_price" numeric(18,6),
  "lease_trade_exclude_tax_price" numeric(18,6),
  "trade_price" numeric(18,6),
  "trade_exclude_tax_price" numeric(18,6),
  "settlement_price" numeric(18,6),
  "fare_price" numeric(18,6),
  "fare_exclude_tax_price" numeric(18,6),
  "service_fee_price" numeric(18,6),
  "service_exclude_tax_fee_price" numeric(18,6),
  "maintenance_fee_price" numeric(18,6),
  "maintenance_exclude_tax_fee_price" numeric(18,6),
  "from_site_id" character varying(64),
  "from_site_name" character varying(128),
  "to_site_id" character varying(64),
  "to_site_name" character varying(128),
  "company_id" character varying(64),
  "company_name" character varying(256),
  "one_project_id" character varying(64),
  "one_project_name" character varying(256),
  "two_project_id" character varying(64),
  "two_project_name" character varying(256),
  "two_project_code" character varying(64),
  "department_id" character varying(64),
  "department_name" character varying(128),
  "customer_level" character varying(32),
  "industry_id" character varying(64),
  "industry_name" character varying(128),
  "estimate_cycle" character varying(32),
  "erp_code" text,
  "erp_name" text,
  "rental_tax_ratio" numeric(8,4),
  "rental_trade_tax_ratio" numeric(8,4),
  "trade_tax_ratio" numeric(8,4),
  "logistics_tax_ratio" numeric(8,4),
  "service_tax_ratio" numeric(8,4),
  "maintain_tax_ratio" numeric(8,4),
  "start_time" timestamp(6) without time zone,
  "end_time" timestamp(6) without time zone,
  "cost_id" character varying(64),
  "cost_code" character varying(64),
  "cost_settlement_date" character varying(32),
  "cost_include_tax_amount" numeric(18,6),
  "cost_exclude_tax_amount" numeric(18,6),
  "cost_exclude_tax_sales_amount" numeric(18,6),
  "cost_exclude_rent_trade_amount" numeric(18,6),
  "cost_exclude_trade_amount" numeric(18,6),
  "cost_exclude_tax_rental_amount" numeric(18,6),
  "cost_exclude_tax_operate_amount" numeric(18,6),
  "cron_type" character varying(8),
  "product_one_category_code" character varying(64),
  "product_one_category_name" character varying(128),
  "out_scan_num" integer,
  "sign_scan_num" integer,
  "first_term" boolean,
  "last_term" boolean,
  "cycle_type" character varying(8),
  "charge_start_time" timestamp(6) without time zone,
  "charge_end_time" timestamp(6) without time zone,
  "order_from_type" character varying(32),
  "charge_cycle" character varying(32),
  "cost_extra_exclude_amount" numeric(18,6),
  "calculate_time" timestamp(6) without time zone,
  "heavy_hedge_flag" boolean,
  "costed_time" character varying(16),
  "extra_flag" boolean,
  "rent_trade_num" numeric(18,6),
  "trade_num" numeric(18,6),
  "attribution_id" character varying(64),
  "attribution_name" character varying(128),
  "team_leader_id" character varying(64),
  "team_leader_name" character varying(128),
  "calculate_start_time" timestamp(6) without time zone,
  "trip_settlement_id" character varying(64),
  "trip_settlement_no" character varying(64),
  "overdue_price" numeric(18,6),
  "cost_exclude_tax_fare_amount" numeric(18,6),
  "cost_exclude_tax_service_fee_amount" numeric(18,6),
  "link_send_demand_id" character varying(64),
  "link_send_demand_no" character varying(64),
  "invoiced_time" timestamp(6) without time zone,
  "custom_material_price" numeric(18,6),
  "custom_material_exclude_tax_price" numeric(18,6),
  "cost_exclude_tax_custom_material_amount" numeric(18,6),
  "adjust_flag" boolean,
  "cost_adjust_exclude_amount" numeric(18,6),
  "service_fee_node" character varying(8),
  "return_fare_node" character varying(8),
  "settlement_type" character varying(32),
  "quantity_type" character varying(32),
  "year_days" integer,
  "send_fare_price" numeric(18,6),
  "send_fare_exclude_tax_price" numeric(18,6),
  "return_fare_price" numeric(18,6),
  "return_fare_exclude_tax_price" numeric(18,6),
  "send_fare_num" numeric(18,6),
  "receive_fare_num" numeric(18,6),
  "service_fee_num" numeric(18,6),
  "maintenance_fee_num" numeric(18,6),
  "billing_time" timestamp(6) without time zone,
  "bill_type" character varying(8),
  "split_day_ratio" numeric(10,6),
  "bill_total_days" integer,
  "split_month_days" integer,
  "create_by" character varying(64),
  "create_name" character varying(128),
  "create_time" timestamp(6) without time zone,
  "last_modify_time" timestamp(6) without time zone,
  "deleted" boolean,
  "account_revenue_exclude_tax_amount" numeric(18,6),
  "last_modify_by" character varying,
  "last_modify_name" character varying
);

DROP TABLE IF EXISTS demo_biz."project_profit_cost" CASCADE;
CREATE TABLE demo_biz."project_profit_cost" (
  "id" character varying,
  "industry_id" character varying,
  "industry_name" character varying,
  "business_type" character varying,
  "receipt_type" character varying,
  "profit_user_id" character varying,
  "profit_user_name" character varying,
  "department_id" character varying,
  "department_name" character varying,
  "company_id" character varying,
  "company_name" character varying,
  "one_project_id" character varying,
  "one_project_name" character varying,
  "two_project_id" character varying,
  "two_project_name" character varying,
  "cost_month" character varying,
  "last_month_balance" numeric,
  "month_balance" numeric,
  "statistics_type" character varying,
  "cost_price" numeric,
  "cost_daily_num" numeric,
  "in_amount" numeric,
  "cost_amount" numeric,
  "fare_cost_amount" numeric,
  "service_cost_amount" numeric,
  "maintenance_cost_amount" numeric,
  "liquid_bag_cost_amount" numeric,
  "profit_amount" numeric,
  "profit_rate" numeric,
  "deleted" boolean,
  "create_by" character varying(36),
  "create_name" character varying(255),
  "create_time" timestamp(6) without time zone,
  "last_modify_by" character varying(255),
  "last_modify_name" character varying(255),
  "last_modify_time" timestamp(6) with time zone,
  "product_one_category_code" character varying,
  "composition_type" smallint,
  "data_type" character varying,
  "record_num" integer,
  "batch_id" character varying,
  "gen_day" timestamp without time zone,
  "tenant_id" character varying(64),
  "profit_source" character varying(8)
);

DROP TABLE IF EXISTS demo_biz."project_profit_cost_record" CASCADE;
CREATE TABLE demo_biz."project_profit_cost_record" (
  "id" character varying,
  "profit_cost_batch_id" character varying,
  "gen_time" timestamp without time zone,
  "deleted" boolean,
  "create_by" character varying(36),
  "create_name" character varying(255),
  "create_time" timestamp(6) without time zone,
  "last_modify_by" character varying(255),
  "last_modify_name" character varying(255),
  "last_modify_time" timestamp(6) with time zone,
  "sort_num" integer,
  "profit_cost_id" character varying
);

